# Generated by Django 3.0.8 on 2020-07-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20200723_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='published_books', to='p_library.Publisher'),
        ),
    ]
